### ISSUE TITLE
Update to be 2.0.0 compatible

### ISSUE THREAD

**Issue by wreis** [dagolden/MongoDBx-Queue#3]
> t/queue.t .............. Can't locate object method "new" via package "MongoDB::Connection" (perhaps you forgot to load "MongoDB::Connection"?) at t/queue.t line 10.

And same for t/search.t; because MongoDB::Connection is DEPRECATED as of version 0.502.0 of the MongoDB CPAN distribution; use MongoDB::MongoClient instead.

**Comment by wreis** [comment]
https://metacpan.org/pod/MongoDB::Upgrading

**Comment by xdg** [comment]
Fixed in latest release.
