### ISSUE TITLE
Improve latency for size for large Queue

### ISSUE THREAD

**Issue by Zer0-Tolerance** [dagolden/MongoDBx-Queue#5]
Hi David,
I just found out that you are not using the fastest method to get the Queue size:

Actual code which is using count_documents() that actually use aggregate and $sum:
`
sub size {
    my ($self) = @_;
    return $self->_mongo_collection( $self->collection_name )->count_documents( {} );
}
`
My proposition which is using estimated_document_count() that actually use "native count" of Mongo plus a timeout to make sure we're not slowing down too much workers :

`
sub size {
    my ($self,$timeout) = @_;
    $timeout=1000;
    return $self->_mongo_collection( $self->collection_name )->estimated_document_count({maxTimeMS => $timeout});
}  
` 

Let me know what you think.

**Comment by xdg** [comment]
It's inherently racy to try to get the actual count, so switching to estimated count is a good idea.

**Comment by xdg** [comment]
Timeout isn't needed -- `estimated_document_count` is based on MongoDB collection metadata, so it's always nearly instantaneous.

**Comment by xdg** [comment]
Released as MongoDBx-Queue-2.002
